//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Id { get; set; }
        public string Facebook { get; set; }
        public string Massenger { get; set; }
        public string Whatsapp { get; set; }
    }
}
