//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Proudct_Id { get; set; }
        public Nullable<int> Offer_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Proudcut Proudcut { get; set; }
    }
}
