//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proudcut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proudcut()
        {
            this.Offer_details = new HashSet<Offer_details>();
            this.Order_Details = new HashSet<Order_Details>();
            this.Proudcut_Details = new HashSet<Proudcut_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Discount_per { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public string Show { get; set; }
        public string Description_A { get; set; }
        public string Description_E { get; set; }
        public string wherestatus { get; set; }
        public Nullable<int> Discount_num { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer_details> Offer_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proudcut_Details> Proudcut_Details { get; set; }
    }
}
